insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,1,0,12,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,1,1,21,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,1,0,17,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,1,1,22,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,2,0,19,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,2,1,23,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,2,0,15,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,2,1,26,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,3,0,11,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,3,1,21,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,3,0,14,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,3,1,23,10);

insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,1,0,13,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,1,1,25,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,1,0,14,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,1,1,21,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,2,0,17,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,2,1,26,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,2,0,18,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,2,1,26,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,3,0,15,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,3,1,23,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,3,0,14,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,3,1,28,10);

insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,1,0,11,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,1,1,22,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,1,0,12,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,1,1,24,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,2,0,13,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,2,1,22,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,2,0,16,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,2,1,25,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,3,0,13,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,3,1,21,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,3,0,14,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,3,1,26,10);


insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,1,0,12,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,1,1,21,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,1,0,17,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,1,1,22,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,2,0,19,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,2,1,23,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,2,0,15,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,2,1,26,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,3,0,11,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,3,1,21,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,3,0,14,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,3,1,23,10);

insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,1,0,13,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,1,1,25,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,1,0,14,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,1,1,21,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,2,0,17,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,2,1,26,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,2,0,18,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,2,1,26,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,3,0,15,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,3,1,23,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,3,0,14,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,3,1,28,10);

insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,1,0,11,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,1,1,22,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,1,0,12,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,1,1,24,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,2,0,13,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,2,1,22,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,2,0,16,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,2,1,25,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,3,0,13,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,3,1,21,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,3,0,14,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,3,1,26,10);


insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,1,0,12,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,1,1,21,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,1,0,17,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,1,1,22,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,2,0,19,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,2,1,23,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,2,0,15,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,2,1,26,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,3,0,11,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,3,1,21,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,3,0,14,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,3,1,23,10);

insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,1,0,13,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,1,1,25,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,1,0,14,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,1,1,21,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,2,0,17,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,2,1,26,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,2,0,18,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,2,1,26,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,3,0,15,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,3,1,23,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,3,0,14,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,3,1,28,10);

insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,1,0,11,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,1,1,22,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,1,0,12,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,1,1,24,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,2,0,13,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,2,1,22,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,2,0,16,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,2,1,25,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,3,0,13,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,3,1,21,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,3,0,14,10);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,3,1,26,10);



insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,1,0,12,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,1,1,21,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,1,0,17,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,1,1,22,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,2,0,19,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,2,1,23,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,2,0,15,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,2,1,26,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,3,0,11,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,3,1,21,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,3,0,14,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',1,3,1,23,30);

insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,1,0,13,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,1,1,25,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,1,0,14,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,1,1,21,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,2,0,17,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,2,1,26,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,2,0,18,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,2,1,26,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,3,0,15,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,3,1,23,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,3,0,14,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',2,3,1,28,30);

insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,1,0,11,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,1,1,22,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,1,0,12,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,1,1,24,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,2,0,13,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,2,1,22,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,2,0,16,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,2,1,25,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,3,0,13,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,3,1,21,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,3,0,14,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(1,'票卡1',3,3,1,26,30);


insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,1,0,12,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,1,1,21,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,1,0,17,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,1,1,22,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,2,0,19,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,2,1,23,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,2,0,15,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,2,1,26,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,3,0,11,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,3,1,21,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,3,0,14,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',1,3,1,23,30);

insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,1,0,13,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,1,1,25,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,1,0,14,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,1,1,21,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,2,0,17,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,2,1,26,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,2,0,18,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,2,1,26,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,3,0,15,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,3,1,23,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,3,0,14,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',2,3,1,28,30);

insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,1,0,11,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,1,1,22,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,1,0,12,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,1,1,24,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,2,0,13,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,2,1,22,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,2,0,16,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,2,1,25,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,3,0,13,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,3,1,21,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,3,0,14,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(2,'票卡2',3,3,1,26,30);


insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,1,0,12,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,1,1,21,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,1,0,17,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,1,1,22,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,2,0,19,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,2,1,23,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,2,0,15,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,2,1,26,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,3,0,11,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,3,1,21,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,3,0,14,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',1,3,1,23,30);

insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,1,0,13,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,1,1,25,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,1,0,14,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,1,1,21,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,2,0,17,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,2,1,26,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,2,0,18,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,2,1,26,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,3,0,15,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,3,1,23,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,3,0,14,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',2,3,1,28,30);

insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,1,0,11,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,1,1,22,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,1,0,12,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,1,1,24,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,2,0,13,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,2,1,22,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,2,0,16,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,2,1,25,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,3,0,13,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,3,1,21,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,3,0,14,30);
insert into afccd.ticket_share_passenger_flow(ticket_id,ticket_name,line_id,station_id,direction,passenger_flow,section) values(3,'票卡3',3,3,1,26,30);