package com.avp.mem.njpb.oauth.entity;

// Generated May 4, 2016 6:03:22 PM by Hibernate Tools 3.2.2.GA

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import org.springframework.security.core.GrantedAuthority;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SysResources generated by hbm2java
 */

/**
 * @author Amber Wang
 * @date 2016-11-30
 */
@Data
@Entity
@Table(name = "sys_resource", schema = "business")
public class SysResource implements GrantedAuthority {

    @JsonIgnore
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;


    @JsonIgnore
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 50)
    @Column(name = "resource_code")
    private String resourceCode;


    @JsonIgnore
    @Column(name = "remove_time")
    private Date removeTime;

    @Override
    public String getAuthority() {
        return this.resourceCode;
    }

}
