#ifndef SHAREDLLWIDGET_GLOBAL_H
#define SHAREDLLWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHAREDLLWIDGET_LIBRARY)
#  define SHAREDLLWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHAREDLLWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHAREDLLWIDGET_GLOBAL_H
