#ifndef MYSHAREDWIDGETDLL_GLOBAL_H
#define MYSHAREDWIDGETDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYSHAREDWIDGETDLL_LIBRARY)
#  define MYSHAREDWIDGETDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MYSHAREDWIDGETDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MYSHAREDWIDGETDLL_GLOBAL_H
